apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-gemini-deployment
  labels:
    app: devops-gemini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-gemini
  template:
    metadata:
      labels:
        app: devops-gemini
    spec:
      containers:
      - name: gemini-app-container
        image: tamilmani5297/devops-gemini-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GEMINI_API_KEY
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"