apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
data:
  # Paste your base64-encoded string below
  GEMINI_API_KEY: QVEuQWI4Uk42SXQtdFBWRmFVcjNwd0ZUY3ZiR01oMzJnZDZ1X0pDZEsxblJjVHNTVkZOZkE=
